//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWcfClient.SimpleWcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MathInput", Namespace="http://schemas.datacontract.org/2004/07/SimpleWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class MathInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FirstNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecondNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstNumber {
            get {
                return this.FirstNumberField;
            }
            set {
                if ((this.FirstNumberField.Equals(value) != true)) {
                    this.FirstNumberField = value;
                    this.RaisePropertyChanged("FirstNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecondNumber {
            get {
                return this.SecondNumberField;
            }
            set {
                if ((this.SecondNumberField.Equals(value) != true)) {
                    this.SecondNumberField = value;
                    this.RaisePropertyChanged("SecondNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MathOutput", Namespace="http://schemas.datacontract.org/2004/07/SimpleWcfService.Models")]
    [System.SerializableAttribute()]
    public partial class MathOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimpleWcfService.IMath")]
    public interface IMath {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/Add", ReplyAction="http://tempuri.org/IMath/AddResponse")]
        SimpleWcfClient.SimpleWcfService.MathOutput Add(SimpleWcfClient.SimpleWcfService.MathInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/Add", ReplyAction="http://tempuri.org/IMath/AddResponse")]
        System.Threading.Tasks.Task<SimpleWcfClient.SimpleWcfService.MathOutput> AddAsync(SimpleWcfClient.SimpleWcfService.MathInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/Div", ReplyAction="http://tempuri.org/IMath/DivResponse")]
        SimpleWcfClient.SimpleWcfService.MathOutput Div(SimpleWcfClient.SimpleWcfService.MathInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/Div", ReplyAction="http://tempuri.org/IMath/DivResponse")]
        System.Threading.Tasks.Task<SimpleWcfClient.SimpleWcfService.MathOutput> DivAsync(SimpleWcfClient.SimpleWcfService.MathInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/Mul", ReplyAction="http://tempuri.org/IMath/MulResponse")]
        SimpleWcfClient.SimpleWcfService.MathOutput Mul(SimpleWcfClient.SimpleWcfService.MathInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/Mul", ReplyAction="http://tempuri.org/IMath/MulResponse")]
        System.Threading.Tasks.Task<SimpleWcfClient.SimpleWcfService.MathOutput> MulAsync(SimpleWcfClient.SimpleWcfService.MathInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/Sub", ReplyAction="http://tempuri.org/IMath/SubResponse")]
        SimpleWcfClient.SimpleWcfService.MathOutput Sub(SimpleWcfClient.SimpleWcfService.MathInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/Sub", ReplyAction="http://tempuri.org/IMath/SubResponse")]
        System.Threading.Tasks.Task<SimpleWcfClient.SimpleWcfService.MathOutput> SubAsync(SimpleWcfClient.SimpleWcfService.MathInput input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMathChannel : SimpleWcfClient.SimpleWcfService.IMath, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathClient : System.ServiceModel.ClientBase<SimpleWcfClient.SimpleWcfService.IMath>, SimpleWcfClient.SimpleWcfService.IMath {
        
        public MathClient() {
        }
        
        public MathClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SimpleWcfClient.SimpleWcfService.MathOutput Add(SimpleWcfClient.SimpleWcfService.MathInput input) {
            return base.Channel.Add(input);
        }
        
        public System.Threading.Tasks.Task<SimpleWcfClient.SimpleWcfService.MathOutput> AddAsync(SimpleWcfClient.SimpleWcfService.MathInput input) {
            return base.Channel.AddAsync(input);
        }
        
        public SimpleWcfClient.SimpleWcfService.MathOutput Div(SimpleWcfClient.SimpleWcfService.MathInput input) {
            return base.Channel.Div(input);
        }
        
        public System.Threading.Tasks.Task<SimpleWcfClient.SimpleWcfService.MathOutput> DivAsync(SimpleWcfClient.SimpleWcfService.MathInput input) {
            return base.Channel.DivAsync(input);
        }
        
        public SimpleWcfClient.SimpleWcfService.MathOutput Mul(SimpleWcfClient.SimpleWcfService.MathInput input) {
            return base.Channel.Mul(input);
        }
        
        public System.Threading.Tasks.Task<SimpleWcfClient.SimpleWcfService.MathOutput> MulAsync(SimpleWcfClient.SimpleWcfService.MathInput input) {
            return base.Channel.MulAsync(input);
        }
        
        public SimpleWcfClient.SimpleWcfService.MathOutput Sub(SimpleWcfClient.SimpleWcfService.MathInput input) {
            return base.Channel.Sub(input);
        }
        
        public System.Threading.Tasks.Task<SimpleWcfClient.SimpleWcfService.MathOutput> SubAsync(SimpleWcfClient.SimpleWcfService.MathInput input) {
            return base.Channel.SubAsync(input);
        }
    }
}
